# QualiSpeech Dataset Analysis

This notebook downloads and analyzes the `tsinghua-ee/QualiSpeech` dataset from Hugging Face, using a local `data-temp` cache directory. It also saves split-level metadata CSV exports for easy inspection.

In [6]:
from pathlib import Path
import pandas as pd
from datasets import load_dataset

DATA_ROOT = Path('data-temp')
CACHE_DIR = DATA_ROOT / 'hf_cache'
DATA_ROOT.mkdir(parents=True, exist_ok=True)
CACHE_DIR.mkdir(parents=True, exist_ok=True)

dataset = load_dataset('tsinghua-ee/QualiSpeech', cache_dir=str(CACHE_DIR))
print('Dataset loaded into cache_dir:', CACHE_DIR.resolve())
print(dataset)

Dataset loaded into cache_dir: /Users/carlschmidt-svejstrup/code/dtu/automatic-speech-assessment/notebooks/data-temp/hf_cache
DatasetDict({
    train: Dataset({
        features: ['id', 'Speed', 'Naturalness', 'Background noise', 'Distortion', 'Listening effort', 'Continuity', 'Overall quality', 'Feeling of voice', 'Noise Description', 'Distortion description', 'Unnatural pause', 'Natural language description'],
        num_rows: 10558
    })
    validation: Dataset({
        features: ['id', 'Speed', 'Naturalness', 'Background noise', 'Distortion', 'Listening effort', 'Continuity', 'Overall quality', 'Feeling of voice', 'Noise Description', 'Distortion description', 'Unnatural pause', 'Natural language description'],
        num_rows: 2167
    })
    test: Dataset({
        features: ['id', 'Speed', 'Naturalness', 'Background noise', 'Distortion', 'Listening effort', 'Continuity', 'Overall quality', 'Feeling of voice', 'Noise Description', 'Distortion description', 'Unnatural pause', 'Natural language description'],
        num_rows: 1852
    })
})

In [7]:
pd.set_option('display.max_columns', None)
rating_cols = [
    'Speed',
    'Naturalness',
    'Background noise',
    'Distortion',
    'Listening effort',
    'Continuity',
    'Overall quality',
    'Feeling of voice',
]

dfs = {}
for split, ds in dataset.items():
    df = ds.to_pandas()
    dfs[split] = df
    print(f'--- {split} ---')
    print('rows:', len(df))
    print('columns:', df.columns.tolist())
    display(df.head(1))
    display(df[rating_cols].describe().transpose())

--- train ---
rows: 10558
columns: ['id', 'Speed', 'Naturalness', 'Background noise', 'Distortion', 'Listening effort', 'Continuity', 'Overall quality', 'Feeling of voice', 'Noise Description', 'Distortion description', 'Unnatural pause', 'Natural language description']

,id,Speed,Naturalness,Background noise,Distortion,Listening effort,Continuity,Overall quality,Feeling of voice,Noise Description,Distortion description,Unnatural pause,Natural language description
0,sys01tts-0000000.wav,2,5,5,5,5,5,5,A woman's voice with a rising and falling tone...,Not noticeable,Not distorted,Very smooth,The speech sample exhibits exceptional quality...

                    count      mean       std  min  25%  50%  75%  max
Speed             10558.0  3.101250  0.530474  1.0  3.0  3.0  3.0  5.0
Naturalness       10558.0  2.998579  1.207746  1.0  2.0  3.0  4.0  5.0
Background noise  10558.0  4.354802  1.041204  1.0  4.0  5.0  5.0  5.0
Distortion        10558.0  3.683842  1.190354  1.0  3.0  4.0  5.0  5.0
Listening effort  10558.0  3.917598  1.176332  1.0  3.0  4.0  5.0  5.0
Continuity        10558.0  4.123887  1.154453  1.0  3.0  5.0  5.0  5.0
Overall quality   10558.0  3.210646  0.965715  1.0  3.0  3.0  4.0  5.0

--- validation ---
rows: 2167
columns: ['id', 'Speed', 'Naturalness', 'Background noise', 'Distortion', 'Listening effort', 'Continuity', 'Overall quality', 'Feeling of voice', 'Noise Description', 'Distortion description', 'Unnatural pause', 'Natural language description']

,id,Speed,Naturalness,Background noise,Distortion,Listening effort,Continuity,Overall quality,Feeling of voice,Noise Description,Distortion description,Unnatural pause,Natural language description
0,sys01tts-0000062.wav,2,1,5,2,1,4,2,A middle-aged man's deep voice with a mechanic...,Not noticeable,There is pitch distortion with mechanical soun...,0.2-0.4s,The speech sample presents a mix of qualities....

                   count      mean       std  min  25%  50%  75%  max
Speed             2167.0  3.104753  0.479121  1.0  3.0  3.0  3.0  5.0
Naturalness       2167.0  2.746654  1.042033  1.0  2.0  3.0  3.0  5.0
Background noise  2167.0  4.370097  1.004418  1.0  4.0  5.0  5.0  5.0
Distortion        2167.0  3.585141  1.168619  1.0  3.0  3.0  5.0  5.0
Listening effort  2167.0  3.924781  1.167571  1.0  3.0  4.0  5.0  5.0
Continuity        2167.0  4.067836  1.143658  1.0  3.0  5.0  5.0  5.0
Overall quality   2167.0  3.125981  0.921330  1.0  3.0  3.0  4.0  5.0

--- test ---
rows: 1852
columns: ['id', 'Speed', 'Naturalness', 'Background noise', 'Distortion', 'Listening effort', 'Continuity', 'Overall quality', 'Feeling of voice', 'Noise Description', 'Distortion description', 'Unnatural pause', 'Natural language description']

,id,Speed,Naturalness,Background noise,Distortion,Listening effort,Continuity,Overall quality,Feeling of voice,Noise Description,Distortion description,Unnatural pause,Natural language description
0,sys01tts-0000068.wav,5,5,5,5,2,5,5,A middle-aged man's deep voice with a normal tone,Not noticeable,Not distorted,Very smooth,The speech sample exhibits exceptional quality...

                   count      mean       std  min  25%  50%  75%  max
Speed             1852.0  2.983801  0.380163  1.0  3.0  3.0  3.0  5.0
Naturalness       1852.0  3.308855  1.292737  1.0  2.0  3.0  5.0  5.0
Background noise  1852.0  4.439525  0.920452  1.0  4.0  5.0  5.0  5.0
Distortion        1852.0  3.861231  1.107739  1.0  3.0  4.0  5.0  5.0
Listening effort  1852.0  3.861231  1.058866  1.0  3.0  4.0  5.0  5.0
Continuity        1852.0  4.259179  1.143321  1.0  4.0  5.0  5.0  5.0
Overall quality   1852.0  3.374190  1.149939  1.0  3.0  3.0  4.0  5.0

In [8]:
for split, df in dfs.items():
    print(f'Top 5 Overall quality examples in {split}')
    display(df.sort_values('Overall quality', ascending=False).head(5))

    print(f'Bottom 5 Overall quality examples in {split}')
    display(df.sort_values('Overall quality', ascending=True).head(5))

Top 5 Overall quality examples in train

,id,Speed,Naturalness,Background noise,Distortion,Listening effort,Continuity,Overall quality,Feeling of voice,Noise Description,Distortion description,Unnatural pause,Natural language description
0,sys01tts-0000000.wav,2,5,5,5,5,5,5,A woman's voice with a rising and falling tone...,Not noticeable,Not distorted,Very smooth,The speech sample exhibits exceptional quality...
2531,sys0giga-0001931.wav,3,5,5,5,5,5,5,A middle-aged woman with deep voice that makes...,not noticeable,not distorted,very smooth,The speech sample exhibits exceptional quality...
2529,sys0giga-0001929.wav,3,5,5,5,5,5,5,A young woman with bright voice that makes peo...,not noticeable,not distorted,very smooth,The speech sample exhibits exceptional quality...
2528,sys0giga-0001928.wav,4,5,5,5,5,5,5,A young woman with bright voice that makes peo...,not noticeable,not distorted,very smooth,The speech sample exhibits exceptional quality...
2527,sys0giga-0001927.wav,3,5,5,5,5,5,5,A middle-aged man with deep voice that makes p...,not noticeable,not distorted,very smooth,The speech sample exhibits exceptional quality...

Bottom 5 Overall quality examples in train

,id,Speed,Naturalness,Background noise,Distortion,Listening effort,Continuity,Overall quality,Feeling of voice,Noise Description,Distortion description,Unnatural pause,Natural language description
4895,sysnists-0002295.wav,3,2,3,2,2,1,1,A young man's deep voice,There is buzzing sound in the audio from 0 to ...,the sounds like a patchwork from 0 to 9.9 seconds,0-9.9s,The speech sample presents a noticeable level ...
5305,sysnists-0002705.wav,3,1,2,1,1,1,1,the harsh and mehcanical voice of a woman,there is a noise from the music playing from 3...,There is a voice feels distorted with cracklin...,0-8.5s,The speech sample exhibits significant backgro...
5304,sysnists-0002704.wav,3,2,3,1,1,1,1,the mechanical voice of a woman but with human...,there is a noise like the electric current fro...,There is a voice feels distorted with cracklin...,0-7.5s,The speech sample presents several significant...
4503,sysnists-0001903.wav,3,1,3,1,2,1,1,"An adult male voice, alto, speaks at a moderat...",There's a background noise like electricity si...,There is pitch distortion with mechanical soun...,1.3-6.5s,The speech sample presents several significant...
4504,sysnists-0001904.wav,3,1,3,1,2,1,1,"An adult male voice, alto, speaks at a moderat...",There are noises in the background that sound ...,There is pitch distortion with mechanical soun...,0-7.9s,The speech sample presents several significant...

Top 5 Overall quality examples in validation

,id,Speed,Naturalness,Background noise,Distortion,Listening effort,Continuity,Overall quality,Feeling of voice,Noise Description,Distortion description,Unnatural pause,Natural language description
2166,sys0ce8e-uttae192e8.wav,3,5,5,5,5,5,5,A young woman's sweet voice with a rising and ...,Not noticeable,Not distorted,Very smooth,The speech sample exhibits exceptional quality...
745,sysnisvs-0000485.wav,3,5,5,5,5,5,5,a young man's deep voice with a gentle tone th...,not noticeable,not distorted,very smooth,The speech sample exhibits exceptional quality...
807,sysnisvs-0000547.wav,4,5,5,5,5,5,5,A young man's voice with a fast tone.,Not noticeable.,Not distorted.,Very smooth.,The speech sample exhibits exceptional quality...
189,sys1giga-0000129.wav,3,5,5,5,5,5,5,A young man's voice that gives someone a feeli...,not noticeable,not distorted,very smooth,The speech sample exhibits exceptional quality...
805,sysnisvs-0000545.wav,3,5,5,5,5,5,5,A middle-aged woman's voice with a lively tone.,Not noticeable.,Not distorted.,Very smooth.,The speech sample exhibits exceptional quality...

Bottom 5 Overall quality examples in validation

,id,Speed,Naturalness,Background noise,Distortion,Listening effort,Continuity,Overall quality,Feeling of voice,Noise Description,Distortion description,Unnatural pause,Natural language description
1083,sysnisvs-0000823.wav,3,2,2,3,1,3,1,There is the audio in very low voice and serio...,There is the noise that is similar to the soun...,There is pitch distortion with intermittent el...,0-9s,The speech sample presents significant challen...
1293,sys0fb9c-utta31c1df.wav,3,1,3,3,1,1,1,"An adult male's voice, slightly low in pitch, ...",There is an indoor background noise that sound...,There is splicing and synthesis type distortio...,0.2-2.8s,The speech sample presents several challenges ...
1766,sysf7bda-utt93f3607.wav,3,1,2,1,1,1,1,"An adult female voice, relatively mature, calm...",There's a high frequency buzzing noise in the ...,There is pitch distortion with mechanical soun...,0.3-4.1s,The speech sample presents significant challen...
1768,sysf7bda-uttcffa027.wav,3,1,5,1,3,1,1,"An adult female voice, mature and calm in tone...",not noticeable,"There is contains mechanical sound, intermitte...",0.4-6.6s,The speech sample presents a very low level of...
1776,sysd79da-utt11b18cf.wav,3,1,2,2,1,3,1,A woman's voice,There is crackling and buzzing sound in the au...,There is pitch distortion with mechanical soun...,2-2.5s,The speech sample presents significant challen...

Top 5 Overall quality examples in test

,id,Speed,Naturalness,Background noise,Distortion,Listening effort,Continuity,Overall quality,Feeling of voice,Noise Description,Distortion description,Unnatural pause,Natural language description
0,sys01tts-0000068.wav,5,5,5,5,2,5,5,A middle-aged man's deep voice with a normal tone,Not noticeable,Not distorted,Very smooth,The speech sample exhibits exceptional quality...
310,sys2giga-0000250.wav,3,5,5,5,5,5,5,A middle-aged man's deep voice with a gentle t...,not noticeable,not distorted,very smooth,The speech sample exhibits exceptional quality...
341,sys2giga-0000281.wav,3,5,5,5,5,5,5,A middle-aged woman's voice with a gentle tone...,not noticeable,not distorted,very smooth,The speech sample exhibits exceptional quality...
339,sys2giga-0000279.wav,2,5,5,5,5,5,5,A middle-aged woman's voice with a gentle tone...,not noticeable,not distorted,very smooth,The speech sample exhibits exceptional quality...
338,sys2giga-0000278.wav,3,5,5,5,5,5,5,A young man's deep voice with a cheerful tone ...,not noticeable,not distorted,very smooth,The speech sample exhibits exceptional quality...

Bottom 5 Overall quality examples in test

,id,Speed,Naturalness,Background noise,Distortion,Listening effort,Continuity,Overall quality,Feeling of voice,Noise Description,Distortion description,Unnatural pause,Natural language description
687,sysnistf-0000227.wav,3,2,3,1,1,2,1,A man's voice that is mostly distorted.,There is background noise similar to drilling ...,There is distortion with mechanical sound and ...,2.5-3.5s,The speech sample presents several significant...
902,sysnistp-0000202.wav,2,1,5,1,1,1,1,"An adult male voice, a deeper, calm tone, spea...",not noticeable,The audio contains mechanical-sounding distort...,0.3-5.4s,The speech sample presents a range of quality ...
903,sysnistp-0000203.wav,2,1,5,1,1,1,1,"An adult male voice, deep, calm tone, slightly...",not noticeable,There is pitch distortion with mechanical soun...,0.3-7.3s,The speech sample presents a range of quality ...
904,sysnistp-0000204.wav,2,1,5,1,1,1,1,"The voice of an adult woman, with a low and ca...",not noticeable,The audio contains mechanical-sounding distort...,0.6-7.5s,The speech sample presents a notable absence o...
815,sysnistp-0000115.wav,2,1,4,1,2,1,1,A middle-aged man's deep voice but is seriousl...,There is background noise similar to the sound...,There is voice distortion with mechanical soun...,0.5-6.7s,The speech sample presents significant challen...

In [9]:
for split, df in dfs.items():
    out_file = DATA_ROOT / f'QualiSpeech_{split}.csv'
    df.to_csv(out_file, index=False)
    print('Saved metadata CSV:', out_file)

Saved metadata CSV: data-temp/QualiSpeech_train.csv
Saved metadata CSV: data-temp/QualiSpeech_validation.csv
Saved metadata CSV: data-temp/QualiSpeech_test.csv

In [12]:
audio_dir = Path('data/QualiSpeech')

if not audio_dir.exists():
    print('QualiSpeech audio data not found locally.')
    print('Please download the audio data from: https://zenodo.org/records/10606702')
    print('Download the "QualiSpeech.zip" file (1.2GB) and unzip it into data/QualiSpeech/')
    print('Then re-run this cell.')
else:
    print('Audio data already exists in:', audio_dir)
    wav_files = list(audio_dir.glob('**/*.wav'))
    print(f'Found {len(wav_files)} wav files in {audio_dir}')
    if wav_files:
        print('Sample files:', [f.name for f in wav_files[:5]])
        # Load a sample audio
        import librosa
        sample_audio, sr = librosa.load(wav_files[0], sr=None)
        print(f'Sample audio loaded: {len(sample_audio)} samples at {sr} Hz')

QualiSpeech audio data not found locally.
Please download the audio data from: https://zenodo.org/records/10606702
Download the "QualiSpeech.zip" file (1.2GB) and unzip it into data/QualiSpeech/
Then re-run this cell.